# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee4aaa1b136cf1742bbf83b323cbb8a419158ecb383efd8353e828116bf7d9a96272133a5ec58bdc13fd69e9a8944029fc42ee9797ec7c07c902682e306c1cb

test:
  secret_key_base: b56e8bae7bef11add0679d806c6984d062b3489fff664e66e79cd565e01960381afd991389ef4b54fa63587da8781d43380040960bbd4f9967ace80a4b153beb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
